### ISSUE TITLE
XFCurvedCornersLabelControl issue

### ISSUE THREAD

**Issue by JimmyPun610** [UdaraAlwis/Xamarin-Playground#1]
Does it work with converter?
Seem like the CurvedBackgroundColor is not updated by converter

**Comment by JimmyPun610** [comment]
Fixed by using ElementPropertyChanged Event to redraw the background.
And fire PropertyChanged event on set CurvedBackgroundColor

**Comment by UdaraAlwis** [comment]
@JimmyPun610 Yes that is correct, as you can see I have left out the run-time binding handling deliberately, since my primary objective here was simply to do a one time rendering of the CurvedBackgroundColor and CurvedCornerRadius properties. 
I was assuming anyone could wire-up that easy part themselves without having to spoon feed everything to the audience ;) 
Anyways Thanks for informing, and as per your request I have added the OnElementPropertyChanged handling in the custom renderers. :) 
Cheers!

**Comment by UdaraAlwis** [comment]
PS: I wouldn't name this as an issue though, since I've deliberately left it out as I explained above. Thanks.
