### ISSUE TITLE
FindViewById<Android.Support.V7.Widget.Toolbar>(Resource.Id.toolbar); is always returning null - XFNavBarBackBtnClickOverride

### ISSUE THREAD

**Issue by LeoJHarris** [UdaraAlwis/Xamarin-Playground#4]
Hi @UdaraAlwis I have run your example code and it works fine, when I copy what you have to my project the tool bar on the line Android.Support.V7.Widget.Toolbar toolbar = this.FindViewById<Android.Support.V7.Widget.Toolbar>(Resource.Id.toolbar); is always null? I can seem to understand what would be causing this, I have the toolbar.xaml and using the same theme. Can you provide some additional details on the configuration you have set that has allowed you to get the toolbar if any? I am thinking it might be do with your older versions of the android support libs? I am at a loss how this is always null??

**Comment by UdaraAlwis** [comment]
Interesting. Nope I'm not using any other modifications for the above situation, whatever in the MainActivity should suffice. It seems like an issue with the Xamarin.Forms versioning or the Android support library versions in your solution. Could you share your solution by any chance?

**Comment by LeoJHarris** [comment]
Ill more then happy to get a sample very shortly.

**Comment by LeoJHarris** [comment]
[Sample.zip](https://github.com/UdaraAlwis/Xamarin-Playground/files/1921639/Sample.zip)

![capture](https://user-images.githubusercontent.com/5468757/38899154-2b6ab8bc-42eb-11e8-818f-859536508684.PNG)

See attached sample repo. I have created a clone and stripped out some pages and class etc. Just leaving what is useful to look through for this. 

I spent almost an entire day going through everything that could be different. Very odd, but could be something so simple I have overlooked.

Love your samples and work!

**Comment by UdaraAlwis** [comment]
Ok looking at your profile, there's couple of things, you have updated all the Xamarin.Android dependencies to the latest versions, which is something you should completely avoid. Instead make sure to keep the Xamarin.Forms version up to date, which will automatically update the "necessary and compatible" Xamarin.Android dependencies for that specific version. I wasn't even able to compile your project due to missing resources on Android dependencies. The issue you're having could be due to few other issues including the Compilation and minimum support version of Android manifest.
Anyways here's some alternative solution I found for your issue: https://forums.xamarin.com/discussion/56946/how-to-use-material-design-toolbar-in-android-when-building-app-with-xamarin-forms
My best bet would be create a new project from scratch without updating the Xamarin.Android dependencies manually, and see if you still can't retrieve the toolbar instance, if not try things step by step according to the above link.
Cheers!

**Comment by LeoJHarris** [comment]
Thanks for the response unfortunately same issue is happening, I tried the link above without success. 

Odd you were unable to compile as a I checked the project by downloaded the sample and deployed fine.

In any event I did create a fresh app project from scratch and only updating Xamarin.forms and still returning null, am using lower dependencies as suggested - same issue, I even copied your android project and dropped that into my solution and toolbar still returned null for me. 

One thing maybe worth noting was in your sample that if i unloaded your portable project then deployed and ran the android project it was returning null, and when I loaded the portable project again I could get access to toolbar and was not null. Could it be an issue somewhere within the portable project? Because everything is an exact copy in the android project from copying your android project from your sample, have kinda run out of ideas to solve looking in the android project

I had a look at the xamarin sample on github here: https://github.com/xamarin/monodroid-samples/tree/master/Supportv7/AppCompat/Toolbar/Supportv7Toolbar and I agree we should be only using the latest Xamarin forms, hoever their sample has updated the packages to use the latest Xamarin.Android dependencies, which suggests this cant be the root of the problem.

Appreciate your input... just trying to get ideas on how to solve this.

**Comment by UdaraAlwis** [comment]
Your project didn't compile on my PC because I hadn't installed the latest Android SDK builds in my computer, and yours did because you had them installed probably. This shouldn't be a problem at all if there were a minimum compatibility between your Xamarin.Forms and Xamarin.Android dependencies.

I highly doubt if PCL project has anything to do with this at all, because its just a non-native dependent dll. I'm pretty sure this has something to do with your Android run time or your the Android version your locally compiling against. As a practice I never set lower than Android 5.0 in my solutions. Could you share the Android version of the device or emulator you're testing? And go to the Android manifest and send me a screenshot so I can take a look at the minimum version your project supports and the one it uses for compilation?

**Comment by LeoJHarris** [comment]
Sure, the devices I am suing are using android 5.1 - API 22 and Android 7.1 - API 25.

![manifest](https://user-images.githubusercontent.com/5468757/39100089-7d5339e2-46d8-11e8-8489-45b933d1609f.PNG)
![manifest2](https://user-images.githubusercontent.com/5468757/39100090-7d97fb7c-46d8-11e8-9439-353e85f0944a.PNG)
![sdk13](https://user-images.githubusercontent.com/5468757/39100255-41a8a1a4-46db-11e8-980d-0d39c7b9ad4e.PNG)

I have installed the android support repo 47.0.0 as well.

My Android SDK platform installations include from Android 8.1 P to Android 5.0 lollipop, although I had changed this from API Level 19 to Android 21 as you mentioned although same issue.

**Comment by LeoJHarris** [comment]
Discovered the issue, turns out the main page of the app must be a NavigationPage or something extending this class, and also below code helped if getting the toolbar in the onCreate returned null

protected override void OnResume()
            {
                Android.Support.V7.Widget.Toolbar toolbar = this.FindViewById<Android.Support.V7.Widget.Toolbar>(Resource.Id.toolbar);
                if (toolbar != null)
                    SetSupportActionBar(toolbar);
            }

**Comment by UdaraAlwis** [comment]
Very interesting. Sorry I couldn't continue looking into it. Thanks for posting the solution.
Cheers! :)

**Comment by cramirezoliveros** [comment]
Hello, Wait, what?  what did you do with MainPage?
in addition to calling the onResume
Please.

**Comment by LeoJHarris** [comment]
@cramirezoliveros I found if your MainPage of your app is not NavigationPage you cannot get access to the toolbar since it doesnt exist. Make sure you initialize it as I mentioned above and it should work.

Call something like this in your MainActivity:

```csharp
LoadApplication(new App());

            SetSupportActionBar(FindViewById<Toolbar>(Resource.Id.toolbar));
```
