### ISSUE TITLE
Master Details Xamarin form with side menu then OnOptionsItemSelected not working in XFNavBarBackBtnClickOverride

### ISSUE THREAD

**Issue by pritish5** [UdaraAlwis/Xamarin-Playground#8]
I am facing 1 problem for android `OnOptionsItemSelected` not calling on back button in `XFNavBarBackBtnClickOverride` project.

I have master details xamarin form ie with Side menu page inside it i am rendering the all child page. so when I click on the navigation back bar item `OnOptionsItemSelected` this override method is not fired.

Please let me know your thoughts on it. How I can achieve this.

**Comment by Depechie** [comment]
Had same issue!
There seems to be a Xamarin Forms framework problem that will interfere with the OnOptionsItemSelected.
Several people are reporting this in different libraries... ( like here https://github.com/MvvmCross/MvvmCross/issues/3124 )
Only good working solution I found to circumvent this problem is posted here https://forums.xamarin.com/discussion/comment/251227/#Comment_251227

**Comment by scriptBoris** [comment]
But, in MasterDetail page - exception appears when use Navigation.PushAsync(new Page() )
Is there a solution to the problem?

**Comment by SShaw1985** [comment]
https://nicksnettravels.builttoroam.com/?tag=/MvvmCross

describes a workaround

**Comment by UdaraAlwis** [comment]
Seems like the issues is resolved. Cheers!
